### ISSUE TITLE
R CMD check fails with dev roxygen2

### ISSUE THREAD

**Issue by hadley** [ThinkR-open/attachment#48]
══ Failed tests ════════════════════════════════════════════════════════════════
      ── Failure (test-att_from_namespace.R:88:3): bad namespace can be corrected ────
      `att_from_namespace(...)` did not throw the expected error.
      
      [ FAIL 1 | WARN 0 | SKIP 1 | PASS 116 ]
      Error: Test failures
      Execution halted

Possibly because roxygen2 now tries harder to avoid creating a bad NAMESPACE. I'm aiming for a CRAN release May 13.

**Comment by statnmap** [comment]
Thanks. I see where this comes from.  
In the future version of {attachment}, I will check {roxygen2} version in the tests
```r
  if (packageVersion("roxygen2") > "7.1.2") {
    # "must have at least 2 words, not 1"
    expect_warning(att_amend_desc(dummypackage),
                   "must have at least 2 words, not 1")
  }
```

However, I had to change another part of my code. Indeed, `roxygen2::roxygenise()` can not be applied on an external package during `devtools::check()` on non-interactive sessions. I think the `rprojroot()` search find the current Check directory instead of the `package.dir` parameter.
Thus, I had to include it in {withr}:
```r
   withr::with_dir(dirname(path), {
      roxygen2::roxygenise(dirname(path), roclets = NULL)
    })
```
See commit: https://github.com/ThinkR-open/attachment/commit/db8f59e748e99be254db2dbf0df9c473316476ba

**Comment by hadley** [comment]
Hmmm, can you give me a simple reprex of the path problem? I can try to track that down.

**Comment by statnmap** [comment]
Thank you.  
I just created this branch `fail-check-roxygen`: https://github.com/ThinkR-open/attachment/tree/fail-check-roxygen  
This is a reduced version of the package, so that you do not wait too long for the checks.  

I tested using the dev version of {testthat}: 7.1.2.9000
The test to explore is the only one remaining in the "tests/" directory.

- If you run `devtools::test()` in the Console, it works.
- If you run tests from RStudio Build Pane, it works
- If you run `devtools::check()` in the console or in the RStudio build pane, it fails with the following message:


```r
> library(testthat)
> library(attachment)
> 
> test_check("attachment")
Updating dummypackage documentation
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-att_from_namespace.R:8:1): (code run outside of `test_that()`) ──
Error: No root directory found in /tmp/RtmpaOZMN7/attachment.Rcheck/tests/testthat or its parent directories. Root criterion: contains a file "DESCRIPTION" with contents matching "^Package: "
Backtrace:
     ▆
  1. └─attachment::att_from_namespace(...) at test-att_from_namespace.R:8:0
  2.   └─roxygen2::roxygenise(dirname(path), roclets = NULL)
  3.     └─roxygen2:::roxygen_setup(base_path)
  4.       └─roxygen2:::first_time(path)
  5.         └─roxygen2:::roxygen_version()
  6.           ├─stringr::str_trim(desc::desc_get("RoxygenNote", path)[[1]])
  7.           │ └─stringi::stri_trim_both(string)
  8.           └─desc::desc_get("RoxygenNote", path)
  9.             └─description$new(file = file)
 10.               └─desc initialize(...)
 11.                 └─desc:::idesc_create(self, private, cmd, file, text, package)
 12.                   └─desc:::idesc_create_file(self, private, file)
 13.                     └─desc:::find_description(file)
 14.                       └─rprojroot::find_root(rprojroot::is_r_package, dir)

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
Error: Test failures
Execution halted
```

- If you set back {withr} in "R/att_from_namespace.R", it works: https://github.com/ThinkR-open/attachment/blob/5e767aaef70afb41d0b7ead696bb9672a707b2f6/R/att_from_namespace.R#L36

**Comment by hadley** [comment]
Looks like I forgot to pass along `path` to `roxygen_version()`, so please try the latest version.

**Comment by statnmap** [comment]
Perfect. Last version is good to me.  
Thank you.
